services:
  resume:
    image: node:lts
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"

  json-utils:
    build: docker/json-utils
    volumes:
      - .:/usr/app/

  printer:
    image: browserless/chrome
    volumes:
      - ./build:/usr/src/app/workspace/resume:rw

  nginx:
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html:readonly
    ports:
      - "8000:80"